### ISSUE TITLE
Is this basically a static site?

### ISSUE THREAD

**Issue by Lewiscowles1986** [microformats/microformats.io#45]
After working on #41 #42 #43 #44 I see this repo seems to be a static site.

Rails routes shows activestorage url endpoints and a single endpoint for what could be a static page.

Would you be open to a PR converting this to static HTML? It should sure cut down maintenance and make this easier to maintain.

**Comment by aaronpk** [comment]
Yes it is! I just converted everything to flat HTML and dropped all the Ruby stuff. Thanks!
